# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: write DB URL
      run: echo "DB_URL=${{ secrets.DB_URL }}">>application-prod.yml
      working-directory: ./src/main/resources
    - name: write DB_USERNAME
      run: echo "DB_USERNAME=${{ secrets.DB_USERNAME }}">>application-prod.yml
      working-directory: ./src/main/resources
    - name: write DB_PASSWORD
      run: echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}">>application-prod.yml
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build -x test -Pprofile=prod
    - name : Build Docker Image
      run: docker build -t dnwo0719/eco-location-back .
    - name: DockerHub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: DockerHub Push
      run: docker push dnwo0719/eco-location-back
